### ISSUE TITLE
can not use sc-geolocator

### ISSUE THREAD

**Issue by ghost** [safetychanger/sc-geolocator#1]
Hi, im trying to work with your component for polymer 1.0, so i installed it through 
**bower install --save sc-geolocator** 
(in your readme said _bower install --save sc-timeago_, i guess it was a mistake, don't you?) 
and later add the component in my own custom element with
**link rel="import" href="..\bower_components\sc-geolocator\sc-geolocator.html"**
and then inserting the tag sc-geolocator in the same way it appear on your index.html from this repository
But does not work, i think i don't know how to make it work, can you give me a hand please?

**Comment by rubenstolk** [comment]
Hi @osomrepos you're right that was a mistake. Can you elaborate on what is not working exactly?

**Comment by ghost** [comment]
Hello Bro, well i can not say whats is wrong with your custom element, since i made my own. I'm sorry. Just i remember that does not work but not sure why
